[server]
port = 8501
maxUploadSize = 2000
enableCORS = true
headless = true
enableXsrfProtection = true

[theme]
primaryColor = "#667eea"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[browser]
gatherUsageStats = false
